name: WMS Tests CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_VERSION: "8.0.x"
  CONFIG: "Release"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore solution
      run: dotnet restore WMS/WMS.sln

    - name: Build solution
      run: dotnet build WMS/WMS.sln --configuration ${{ env.CONFIG }} --no-restore

    - name: Run tests
      run: dotnet test WMS/WMS.Tests/WMS.Tests.csproj --configuration ${{ env.CONFIG }} --no-build --logger "trx;LogFileName=test-results.trx"
