name: WMS Tests CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOTNET_VERSION: "8.0.x"
  CONFIG: "Release"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore solution
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests
     run: dotnet test WMS.Tests/WMS.Tests.csproj --configuration Release --no-build
